project_id = "kbxdwrvxrnfkqvpselwz"

[functions.send-custom-email]
verify_jwt = false

[functions.send-reservation-email]
verify_jwt = false

[functions.send-laiga-reservation]
verify_jwt = false

[functions.send-repair-request]
verify_jwt = false

[functions.track-visitor-location]
verify_jwt = false

[functions.verify-recaptcha]
verify_jwt = false
